-- OffHands: Autonomous AI Business Schema
-- Run in Supabase SQL Editor

-- Business state (single row — the "brain")
CREATE TABLE IF NOT EXISTS business_state (
  id INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  hands_off BOOLEAN NOT NULL DEFAULT false,
  total_revenue DECIMAL(10,2) NOT NULL DEFAULT 0,
  orders_fulfilled INT NOT NULL DEFAULT 0,
  products_listed INT NOT NULL DEFAULT 0,
  last_tick_at TIMESTAMPTZ,
  strategy JSONB NOT NULL DEFAULT '{"focus":"growth","price_multiplier":1.0}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO business_state (id) VALUES (1) ON CONFLICT DO NOTHING;

-- Digital products (agent-created)
CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL DEFAULT 4.99,
  content TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'brain-fuel',
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  safety_score INT NOT NULL DEFAULT 100,
  created_by TEXT NOT NULL DEFAULT 'creator-agent',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Customer orders
CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID REFERENCES products(id),
  customer_email TEXT NOT NULL,
  customer_goal TEXT,
  paypal_order_id TEXT UNIQUE,
  paypal_capture_id TEXT,
  amount DECIMAL(10,2) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'fulfilled', 'failed')),
  deliverable TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  fulfilled_at TIMESTAMPTZ
);

-- Agent activity log (live feed)
CREATE TABLE IF NOT EXISTS agent_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent TEXT NOT NULL,
  region TEXT NOT NULL,
  action TEXT NOT NULL,
  detail TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_logs_created ON agent_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_products_status ON products(status);

-- Marketing content (agent-generated)
CREATE TABLE IF NOT EXISTS marketing_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform TEXT NOT NULL DEFAULT 'twitter',
  content TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'posted')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable Realtime for dashboard (ignore if already added)
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE agent_logs;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE orders;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE business_state;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- RLS (public read for demo, service role writes)
ALTER TABLE business_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketing_posts ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "Public read business_state" ON business_state FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE POLICY "Public read products" ON products FOR SELECT USING (status = 'published');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE POLICY "Public read agent_logs" ON agent_logs FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE POLICY "Public read marketing" ON marketing_posts FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Seed starter product
INSERT INTO products (title, description, price, content, status, published_at)
SELECT
  'Brain Fuel Briefing #1',
  'A neuroscience-backed 5-minute read on focus, dopamine, and sustainable productivity.',
  4.99,
  E'# Brain Fuel Briefing #1\n\n## The Prefrontal Protocol\n\nYour prefrontal cortex is the CEO of your brain. When it''s tired, every decision feels harder.\n\n**Three resets that work:**\n1. **90-second breath** — 4 counts in, 6 counts out. Activates parasympathetic calm.\n2. **Single-task lock** — One tab, one task, 25 minutes. Protect working memory.\n3. **Dopamine deposit** — Complete something small first. Momentum compounds.\n\n*Generated by OffHands Motor Cortex Agent*',
  'published',
  now()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE title = 'Brain Fuel Briefing #1');
